### ISSUE TITLE
How to write `Block_modName-Elem`?

### ISSUE THREAD

**Issue by ilyasidorchik** [bem/bem-react#554]
Please, help me get the class of element that changes its style depending on its block.

```
const block = cn('Block') // 'Block'
block({ modName: true }) // 'Block Block_modName'
block({ modName: true })('Element') // Error. Type 'String' has no call signatures
```

Of course I can use `cn('Block_modName')('Element')` but the meaning of the package is lost.

**Comment by yarastqt** [comment]
Hello, it's strange case, u can tell about this?

**Comment by ilyasidorchik** [comment]
I knew from the BEM docs that block [could have modifier](https://en.bem.info/methodology/key-concepts/#modifier). Also I read that block could have element. So I supposed modified block with element had a place to be.

About my example. I have Link component for a common link. In addition, I want special Link component for a link with more clickable zone around. I named it `Link_wrap` and add element `<u>` with classes `Link-U Link_wrap-U` for underlined words.

**Comment by rrabmig** [comment]
Its recommended to use 

```ts
block({ modName: true }) // on root tag

block('Elem') // on elemet tag inside root tag
```

so you get a structure like:

```html
<div class="Block Block_modName">
    <div class="Block-Element">
    ...
    <div>
</div>
```

finally, use selector:

```css
.Block-Element {
    /* 0 1 0*/
    color: red
}

.Block_mod_name .Block-Element {
   /* note that 0 2 0 will override 0 1 0*/
    color: blue
}
```

_Hello from 2026_
